### ISSUE TITLE
Bot unable to repay VAI

### ISSUE THREAD

**Issue by phyzixmusic** [piyanggoon/venus-protocol-bot#1]
I've tried cranking up the liquidity fix in the config file to 20 and it successfully pushed the borrowing limit to 80%. I then manually minted some new VAI to push the borrowing limit to 92%. The bot kept burning gas by repaying 0 

https://bscscan.com/tx/0x81bdfa87945d64852d9a37905b6d3c84b2179f75612dda80f84ba661c6425337

**Comment by piyanggoon** [comment]
Currently, bot use 2 decimal for fix amount, you can fix to 4

**Comment by piyanggoon** [comment]
Currently, i use 2 decimal for calculate soon i will fix it, thx
