### ISSUE TITLE
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by stephane303** [piyanggoon/venus-protocol-bot#2]
After running the bot for a couple of hours I get ;
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

Do you observe the same ?

**Comment by piyanggoon** [comment]
Currently, running 24/7 without problems maybe not enough of memory?

**Comment by stephane303** [comment]
with this:
node --max-old-space-size=2048 app.js, it seems stable

Great code, it's very nice to have a working example !
